language: rust
cache: cargo
env: RUST_BACKTRACE=1

script:
  - cargo update
  - cargo test --all --locked --verbose
  - cargo doc --verbose
  - rustup component add clippy rustfmt
  - cargo clippy --all-targets -- -D warnings
  - cargo fmt --all -- --check

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

  include:
  - rust: stable
    os: linux
  - rust: beta
    os: linux
  - rust: nightly
    os: linux
  - rust: stable
    os: osx

branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    os: linux
    condition: $TRAVIS_RUST_VERSION = stable
