language: rust
cache: cargo
env: # required for allow_failures
rust:
  - stable
  - beta
  - nightly

script:
  - cargo update
  - cargo test --all --locked --verbose
  - cargo doc --verbose
  - rustup component add clippy rustfmt
  - cargo clippy --all-targets -- -D warnings
  - cargo fmt --all -- --check

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
