[package]
name = "webbrowser"
description = "Open URLs in web browsers available on a platform"
version = "0.1.2"
authors = ["Amod Malviya @amodm"]
documentation = "http://code.rootnet.in/webbrowser-rs/webbrowser"
homepage = "https://github.com/amodm/webbrowser-rs"
repository = "https://github.com/amodm/webbrowser-rs"
readme = "README.md"
keywords = ["webbrowser", "web browser", "browser"]
license = "MIT"

[dependencies]
